language: scala

scala:
- 2.12.9

before_install:
- export PATH=${PATH}:./vendor/bundle

install:
- rvm use 2.6.4 --install --fuzzy
- gem install jekyll -v 4.0.0

script:
  - sbt ++$TRAVIS_SCALA_VERSION "publishMicrosite"
