name: sbt-microsites-multiversion
baseurl: /sbt-microsites-multiversion
description: sbt-microsites-multiversion description
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.3.0-SNAPSHOT
include:
- css/monokai.css
- css/codemirror.css
- css/light-palette.css
- css/light-palette.scss
- css/light-style.css
- css/light-style.scss
exclude:
- css
org: default
markdown: kramdown
