name: sbt-microsites-multiversion
baseurl: /sbt-microsites-multiversion/0.2.0
description: sbt-microsites-multiversion description
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.2.0
org: default
markdown: kramdown
