name: sbt-microsites-multiversion
baseurl: ''
description: sbt-microsites-multiversion description
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.0-SNAPSHOT
org: docs
markdown: kramdown
