name: sbt-microsites-multiversion
baseurl: /sbt-microsites-multiversion /next
description: sbt-microsites-multiversion description
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.3.0-SNAPSHOT
org: default
markdown: kramdown
